export const frameworks = {
   "Ideon Flow": [
    { title: "Nome do Projeto", hint: "Escolha um nome claro e memorável.", span: 6 },
{ title: "Objetivo Principal", hint: "O que você quer alcançar ao final do projeto?", span: 6 },
{ title: "Área de Atuação", hint: "Ex.: tecnologia, educação, saúde, entretenimento.", span: 6 },
{ title: "Problema Central", hint: "Qual dor ou necessidade o projeto resolve?", span: 6 },
{ title: "Público-Alvo", hint: "Quem será beneficiado ou impactado?", span: 6 },
{ title: "Nível de Experiência", hint: "Iniciante, intermediário ou avançado.", span: 6 },
{ title: "Recursos Disponíveis", hint: "Tempo, equipe, ferramentas e habilidades já disponíveis.", span: 6 },
{ title: "Orçamento Inicial", hint: "Quanto você está disposto a investir no início?", span: 6 },
{ title: "Prazo Desejado", hint: "Tempo total estimado para concluir o projeto.", span: 6 },
{ title: "Critério de Sucesso", hint: "Como você saberá que o projeto atingiu o objetivo?", span: 6 },
{ title: "Descrição Geral", hint: "Um breve resumo do projeto e sua visão.", span: 12 }

  ],
  "Lean Canvas Expandido": [
    { title: "Nome do Projeto", hint: "Um nome claro e memorável.", span: 6 },
    { title: "Problema", hint: "Que problema real você resolve?", span: 6 },
    { title: "Solução", hint: "Como sua solução endereça o problema?", span: 6 },
    { title: "Proposta de Valor", hint: "O que torna sua solução única?", span: 6 },
    { title: "Público/Segmentos", hint: "Quem são os usuários ou clientes?", span: 6 },
    { title: "Canais", hint: "Como você chega ao público?", span: 6 },
    { title: "MVP", hint: "Qual é o mínimo para testar valor?", span: 6 },
    { title: "Validação", hint: "Como você medirá o sucesso inicial?", span: 6 },
    { title: "OKRs", hint: "Objetivos e resultados-chave.", span: 6 },
    { title: "Custos", hint: "Principais custos.", span: 6 },
    { title: "Receitas", hint: "Fontes de receita.", span: 6 },
    { title: "Descrição", hint:"Breve descrição do projeto.", span:12}
  ],
  "Proposta de Valor (VPC)": [
    { title: "Cliente-Alvo", hint: "Quem é o cliente e contexto?", span: 6 },
    { title: "Tarefas do Cliente", hint: "O que tentam realizar?", span: 6 },
    { title: "Dores", hint: "Obstáculos e frustrações.", span: 6 },
    { title: "Ganhos", hint: "Resultados desejados.", span: 6 },
    { title: "Produtos/Serviços", hint: "O que você oferece?", span: 6 },
    { title: "Aliviadores de Dor", hint: "Como reduz as dores?", span: 6 },
    { title: "Criadores de Ganho", hint: "Como gera ganhos?", span: 6 }
  ],
  "Mini Roadmap de Projeto": [
    { title: "Objetivo", hint: "Resultado principal do período.", span: 12 },
    { title: "Marcos", hint: "Etapas chave.", span: 6 },
    { title: "Tarefas", hint: "Lista priorizada.", span: 6 },
    { title: "Riscos/Dependências", hint: "O que pode impactar.", span: 12 }
  ],
  "Pitch Rápido": [
    { title: "Problema", hint: "", span: 6 },
    { title: "Solução", hint: "", span: 6 },
    { title: "Diferencial", hint: "", span: 6 },
    { title: "Mercado", hint: "", span: 6 },
    { title: "Tração/Provas", hint: "", span: 6 },
    { title: "Call-to-Action", hint: "", span: 6 },
  ],
  "Canvas do IdeiaHub (custom)": [
    { title: "Visão", hint: "Onde queremos chegar?", span: 12 },
    { title: "Usuários", hint: "", span: 6 },
    { title: "Solução", hint: "", span: 6 },
    { title: "Métricas-Chave", hint: "", span: 6 },
    { title: "Experimentos", hint: "", span: 6 },
    { title: "Roadmap", hint: "", span: 12 },
  ],
  "SWOT Simplificado": [
    { title: "Forças", hint: "", span: 6 },
    { title: "Fraquezas", hint: "", span: 6 },
    { title: "Oportunidades", hint: "", span: 6 },
    { title: "Ameaças", hint: "", span: 6 },
  ],
  "Product Management Canvas": [
    { title: "Problema", hint: "", span: 6 },
    { title: "Público", hint: "", span: 6 },
    { title: "Proposta de Valor", hint: "", span: 6 },
    { title: "Métricas", hint: "", span: 6 },
    { title: "Canais", hint: "", span: 6 },
    { title: "Monetização", hint: "", span: 6 },
  ],
  "Roadmap Trimestral": [
    { title: "Q Objetivos", hint: "", span: 12 },
    { title: "Em Andamento", hint: "", span: 6 },
    { title: "Próximo", hint: "", span: 6 },
    { title: "Riscos", hint: "", span: 12 },
  ],
  "Go-To-Market (GTM) Lite": [
    { title: "Segmento-Alvo", hint: "", span: 6 },
    { title: "Proposta de Valor", hint: "", span: 6 },
    { title: "Canais", hint: "", span: 6 },
    { title: "Mensagem", hint: "", span: 6 },
    { title: "Táticas Iniciais", hint: "", span: 12 },
  ],
  "Plano de Entrevista com Clientes": [
    { title: "Objetivo da Entrevista", hint: "", span: 12 },
    { title: "Perfil dos Entrevistados", hint: "", span: 6 },
    { title: "Roteiro de Perguntas", hint: "", span: 6 },
    { title: "Notas", hint: "", span: 12 },
  ],
  "Mapa da Jornada do Cliente (Lite)": [
    { title: "Estágios", hint: "Descoberta > Consideração > Decisão > Retenção", span: 12 },
    { title: "Ações do Cliente", hint: "", span: 12 },
    { title: "Pontos de Dor", hint: "", span: 6 },
    { title: "Oportunidades", hint: "", span: 6 },
  ],
  "Brief de Funcionalidade": [
    { title: "Resumo", hint: "", span: 12 },
    { title: "Problema", hint: "", span: 6 },
    { title: "Solução Proposta", hint: "", span: 6 },
    { title: "Critérios de Aceite", hint: "", span: 12 },
  ],
  "Estratégia de Precificação": [
    { title: "Proposta de Valor", hint: "", span: 12 },
    { title: "Segmentos/Planos", hint: "", span: 6 },
    { title: "Preço Inicial", hint: "", span: 6 },
    { title: "Teste & Validação", hint: "", span: 12 },
  ],
};

export const templates = {
  "Clube de Horta Urbana": {
    
  "Ameaças": "Concorrência de hortas comunitárias, regulamentações locais.",
  "Área de Atuação": "Sustentabilidade, alimentação saudável, comunidade.",
  "Canais": "Parcerias com condomínios, redes sociais locais, feiras de bairro.",
  "Critérios de Aceite": "Horta instalada, 30 participantes ativos, 2 colheitas mensais.",
  "Critério de Sucesso": "Horta instalada, 30 participantes ativos, 2 colheitas mensais.",
  "Custos": "R$ 500 para instalação inicial, R$ 200 mensais de manutenção.",
  "Descrição Geral": "HortaClub conecta moradores urbanos com hortas compartilhadas, promovendo alimentação saudável e sustentabilidade.",
  "Forças": "Interesse crescente por sustentabilidade, comunidade engajada.",
  "Fraquezas": "Dependência de espaço físico, sazonalidade das colheitas.",
  "MVP": "Instalação de 1 horta piloto em um prédio e encontros semanais.",
  "Nome do Projeto": "HortaClub",
  "Nível de Experiência": "Iniciante",
  "Objetivo Principal": "Conectar moradores urbanos com hortas compartilhadas.",
  "OKRs": "O: Validar interesse; KR1: 30 participantes; KR2: 2 colheitas/mês",
  "Oportunidades": "Parcerias com escolas e ONGs, expansão para mais prédios.",
  "Orçamento Inicial": "R$ 500 para instalação inicial, R$ 200 mensais de manutenção.",
  "Prazo Desejado": "3 meses para validação inicial.",
  "Preço Inicial": "R$ 49,90/mês por participante.",
  "Problema": "Moradores urbanos têm pouco acesso a espaços verdes e alimentos frescos.",
  "Problema Central": "Moradores urbanos têm pouco acesso a espaços verdes e alimentos frescos.",
  "Público/Segmentos": "Moradores de apartamentos, síndicos, escolas.",
  "Público-Alvo": "Moradores urbanos, síndicos de prédios, escolas.",
  "Receitas": "R$ 49,90/mês por participante, R$ 200 de patrocínios locais.",
  "Recursos Disponíveis": "Espaço em prédios, voluntários, ferramentas de jardinagem.",
  "Resumo": "HortaClub conecta moradores urbanos com hortas compartilhadas, promovendo alimentação saudável e sustentabilidade.",
  "Solução": "Clubes de hortas compartilhadas em prédios e bairros com kits e mentorias.",
  "Solução Proposta": "Criar hortas urbanas compartilhadas com kits de cultivo e mentorias.",
  "Validação": "Número de participantes ativos e safra colhida em 60 dias."
  },

  "Sistema de Votação Autônomo para Condomínios":
    {
  "nomeDoProjeto": "VotaçãoCondo",
  "Objetivo Principal": "Um aplicativo descentralizado que permite que moradores de condomínios votem em pautas importantes de forma transparente e imutável, sem a necessidade de assembleias presenciais.",
  "Problema": "Assembleias de condomínio são burocráticas, com baixa participação e resultados que geram desconfiança.",
  "Solução": "Uma plataforma baseada em DApps (Aplicativos Descentralizados) que permite a votação online, auditável e imutável.",
  "Solução Proposta": "Criar um sistema de votação para condomínios usando tecnologia blockchain, garantindo transparência e segurança.",
  "Público/Segmentos": "Moradores de condomínios residenciais e comerciais, síndicos, administradoras de condomínios.",
  "Canais": "Parcerias com administradoras de condomínios, associações de síndicos, marketing digital focado em grupos de moradores.",
  "MVP": "Um aplicativo com registro de moradores e votação para uma única pauta, como a eleição do síndico.",
  "Validação": "Implementação em 5 condomínios-piloto, com 80% de participação nas votações em 3 meses.",
  "Critérios de Aceite": "Sistema de votação funcional, relatório de auditoria, 80% de participação nos condomínios-piloto.",
  "OKRs": "O: Aumentar a participação em assembleias; KR1: 80% de participação em 3 meses; KR2: 100% de transparência em pautas votadas.",
  "Forças": "Transparência via blockchain, facilidade de uso, aumento da participação dos moradores.",
  "Fraquezas": "Custo inicial de desenvolvimento, curva de aprendizado para alguns usuários, necessidade de regulamentação.",
  "Oportunidades": "Expansão para assembleias de associações e escolas, integrações com sistemas de gestão de condomínios.",
  "Ameaças": "Desafios de segurança digital, resistência de síndicos a novas tecnologias, regulamentações governamentais.",
  "Resumo": "VotaçãoCondo é um DApp para votações de condomínio, focado em aumentar a participação e garantir a transparência de forma segura.",
  "Área de Atuação": "Propriedade, finanças, comunidade, tecnologia.",
  "Nível de Experiência": "Intermediário a Avançado",
  "Recursos Disponíveis": "Desenvolvedores de blockchain, especialistas em UX/UI, síndicos parceiros.",
  "Prazo Desejado": "6 meses para um MVP funcional e validado.",
  "Critério de Sucesso": "Implementação bem-sucedida em 5 condomínios-piloto e feedback positivo dos moradores."
},
  
  "Correção Colaborativa de Redações": {
    "Problema": "Estudantes carecem de feedback rápido e qualificado.",
    "Solução": "Plataforma com correção por pares e monitores.",
    "Público": "Alunos de ensino médio, cursinhos.",
    "Canais": "Parcerias com escolas, influenciadores educacionais.",
    "MVP": "Turma piloto com 50 alunos e 2 correções semanais.", 
    "Validação": "Taxa de aprovação em simulados 20% maior que média.",
    "OKRs": "O: Melhorar notas; KR1: 80% dos alunos com notas acima de 7; KR2: 90% de feedback positivo.",
    "Forças": "Alta demanda por correção de redações, comunidade escolar engajada.",
    "Fraquezas": "Dependência de voluntários, necessidade de treinamento.", 
    "Oportunidades": "Expansão para outras disciplinas, parcerias com cursinhos.",
    "Ameaças": "Concorrência de plataformas consolidadas, resistência a mudanças.",
    },
  "Feira Online do Bairro": {
    "Problema": "Produtores locais não alcançam compradores digitais.",
    "Solução": "Marketplace hiperlocal com logística colaborativa.",
    "Canais": "Grupos de WhatsApp, associações de bairro.",
    "MVP": "Landing + catálogo simples + entregas em um dia fixo.",
    "Validação": "50 pedidos no primeiro mês e 20% de recompra.",
    "OKRs": "O: Criar comunidade; KR1: 100 usuários ativos no primeiro mês; KR2: 50 pedidos semanais.",
    "Forças": "Apoio à economia local, interesse por produtos frescos.",
    "Fraquezas": "Logística complexa, dependência de tecnologia.",
    "Oportunidades": "Parcerias com feiras e produtores, expansão para outros bairros.",
    "Ameaças": "Concorrência de grandes marketplaces, regulamentações locais.",
  
  },
  "App de Roteiros de Caminhadas Locais": {
    "Problema": "Falta de rotas seguras e interessantes nas redondezas.",
    "Solução": "App com roteiros curados e gamificação.",
    "MVP": "Mapa com 5 rotas e sistema de badges.",
    "Validação": "100 downloads e 50 rotas completadas no primeiro mês.",
    "OKRs": "O: Criar comunidade de caminhantes; KR1: 200 downloads; KR2: 100 rotas completadas.",
    "Forças": "Crescimento do interesse por atividades ao ar livre, comunidade local engajada.",
    "Fraquezas": "Dependência de tecnologia, necessidade de curadoria constante.",
    "Oportunidades": "Parcerias com academias e lojas de esportes, expansão",
    "Ameaças": "Concorrência de apps de caminhada, mudanças climáticas.",

  },
  "Plataforma de Troca de Habilidades": {
    "Problema": "Pessoas querem aprender sem alto custo.",
    "Solução": "Créditos por aula ensinada para aprender outra habilidade.",
    "Público/Segmentos": "Estudantes, profissionais em transição de carreira.",
    "Canais": "Universidades, grupos de interesse, redes sociais.",
    "MVP": "Landing page + 10 aulas disponíveis + sistema de créditos.",
    "Validação": "50 usuários ativos e 100 aulas trocadas no primeiro mês.",
    "OKRs": "O: Criar comunidade de aprendizado; KR1: 200 usuários ativos; KR2: 500 aulas trocadas.",
    "Forças": "Alta demanda por aprendizado acessível, comunidade engajada.", 
    "Fraquezas": "Dependência de voluntários, necessidade de curadoria.",
    "Oportunidades": "Parcerias com escolas e universidades, expansão para outras cidades.",
    "Ameaças": "Concorrência de plataformas consolidadas, resistência a mudanças.",
    
  },
  "Loja Virtual de Produtos Artesanais Locais": {
    "Problema": "Artesãos têm pouca presença online.",
    "Solução": "Loja compartilhada com vitrine e logística simples.",
    "Proposta de Valor":"Teste",
    "Público/Segmentos":"Luiz",
    "Canais":"Canal",
    "MVP":"Produto",
    "Validação":"Valido",
    "OKRs":"kit",
    "Custos":"preço",
    "Receitas":"R$",
    "Forças": "Apoio à economia local, interesse por produtos únicos.",
    "Fraquezas": "Dependência de tecnologia, logística complexa.",
    "Oportunidades": "Parcerias com feiras e eventos locais, expansão para outros bairros.",
    "Ameaças": "Concorrência de grandes marketplaces, regulamentações locais.",
    
  },
  "Painel de Indicadores para Pequenos Negócios": {
    "Problema": "Empreendedores não têm visão consolidada de indicadores.",
    "Solução": "Dashboard simples integrado a planilhas.",
    "Público/Segmentos": "Pequenos empresários, freelancers.",
    "Canais": "Grupos de empreendedores, redes sociais.", 
    "MVP": "Dashboard com 5 indicadores principais e integração com Google Sheets.",
    "Validação": "10 negócios ativos e 50 indicadores visualizados no primeiro mês.",
    "OKRs": "O: Melhorar gestão; KR1: 20 negócios ativos; KR2: 100 indicadores visualizados.",
    "Forças": "Alta demanda por gestão simples, comunidade empreendedora engajada.",
    "Fraquezas": "Dependência de tecnologia, necessidade de treinamento.",
    "Oportunidades": "Parcerias com associações de empreendedores, expansão para outras cidades.",
    "Ameaças": "Concorrência de ferramentas consolidadas, resistência a mudanças",
  },
  "Rede de Apoio a Mães Empreendedoras": {
    "Problema": "Falta de networking e suporte flexível.",
    "Solução": "Comunidade, mentorias e marketplace.",
    "Público/Segmentos": "Mães empreendedoras, freelancers.",
    "Canais": "Grupos de mães, redes sociais, eventos locais.",
    "MVP": "Grupo no WhatsApp + 1 evento mensal + marketplace simples.",
    "Validação": "50 mães ativas e 10 negócios no marketplace no primeiro mês.",
    "OKRs": "O: Criar comunidade de apoio; KR1: 100 mães ativas; KR2: 20 negócios no marketplace.",
    "Forças": "Alta demanda por suporte, comunidade engajada.", 
    "Fraquezas": "Dependência de tecnologia, necessidade de curadoria.",
    "Oportunidades": "Parcerias com escolas e ONGs, expansão para outras cidades.",
    "Ameaças": "Concorrência de grupos consolidados, resistência a mudanças.",  

    
  },
  "Projeto Educacional Gamificado": {
    "Problema": "Baixa motivação em estudos remotos.",
    "Solução": "Metas, missões e recompensas.",
    "Público/Segmentos": "Estudantes do ensino médio, professores.",
    "Canais": "Escolas, redes sociais, influenciadores educacionais.",
    "MVP": "Plataforma com 5 missões e sistema de recompensas.",
    "Validação": "50 alunos ativos e 20% de aumento na participação em 30 dias.",
    "OKRs": "O: Aumentar engajamento; KR1: 100 alunos ativos; KR2: 50% de participação em missões.",
    "Forças": "Interesse crescente por gamificação, comunidade escolar engajada.",  
    "Fraquezas": "Dependência de tecnologia, necessidade de curadoria constante.",
    "Oportunidades": "Parcerias com escolas e ONGs, expansão para outras disciplinas.",
    "Ameaças": "Concorrência de plataformas consolidadas, resistência a mudanças.",
    "Proposta de Valor": "Gamificação do aprendizado para aumentar engajamento.", 
    "Segmentos/Planos": "Estudantes do ensino médio, professores.",
    "Preço Inicial": "R$ 29,90/mês por aluno.",
    "Teste & Validação": "Taxa de participação em missões e feedback dos alunos.",


  },
  "Rede de Troca de Livros": {
   "Problema": "Livros usados acumulam poeira e não são lidos.",
    "Solução": "Plataforma de troca de livros entre usuários.",
    "Público/Segmentos": "Leitores, estudantes, escolas.",
    "Canais": "Grupos de leitura, redes sociais, eventos literários.",
    "MVP": "Landing page com catálogo de 100 livros e sistema de troca.",
    "Validação": "50 trocas realizadas no primeiro mês e 100 usuários ativos.",
    "OKRs": "O: Criar comunidade de leitores; KR1: 200 usuários ativos; KR2: 100 trocas mensais.",
    "Forças": "Interesse crescente por sustentabilidade, comunidade literária engajada.",
    "Fraquezas": "Dependência de tecnologia, necessidade de curadoria constante.",
    "Oportunidades": "Parcerias com editoras e livrarias, expansão para outras cidades.",
    "Ameaças": "Concorrência de plataformas consolidadas, resistência a mudanças.",
  },

  "Central de Ofertas Comunitárias": {
    "Problema": "Ofertas locais se perdem em vários canais.",
    "Solução": "Hub único de promoções do bairro.",
    "Público/Segmentos": "Moradores locais, pequenos comerciantes.",
    "Canais": "Grupos de WhatsApp, redes sociais locais, associações de bairro.",
    "MVP": "Landing page com 10 ofertas e grupo de WhatsApp.",
    "Validação": "100 usuários ativos e 50 ofertas resgatadas no primeiro mês.",
    "OKRs": "O: Criar comunidade de consumo local; KR1: 200 usuários ativos; KR2: 100 ofertas resgatadas.",
    "Forças": "Apoio à economia local, interesse por ofertas exclusivas.",
    "Fraquezas": "Dependência de tecnologia, necessidade de curadoria.",
    "Oportunidades": "Parcerias com comerciantes locais, expansão para outros bairros.",
    "Ameaças": "Concorrência de grandes plataformas, regulamentações locais.",

  },
  "Mercado de Permacultura Urbana":{

  "nomeDoProjeto": "EcoMercado Urbano",
  "Objetivo Principal": " Uma plataforma que conecta produtores de alimentos em pequena escala (hortas em telhados, pequenos quintais) com restaurantes locais e consumidores dispostos a pagar por produtos ultra-locais.",
  "Problema": "Moradores urbanos têm dificuldade em encontrar alimentos frescos e sustentáveis, enquanto pequenos produtores não têm um canal de vendas direto.",
  "Solução": "Uma plataforma online para que produtores de permacultura urbana vendam seus produtos, e consumidores assinem cestas semanais de alimentos locais.",
  "Solução Proposta": "Desenvolver um marketplace que conecte produtores e consumidores de permacultura urbana, com um sistema de assinaturas e entrega direta.",
  "Público/Segmentos": "Consumidores conscientes, moradores urbanos, restaurantes locais, pequenos produtores urbanos.",
  "Canais": "Feiras de bairro, redes sociais (grupos de alimentação saudável), parcerias com cafeterias e restaurantes.",
  "MVP": "Um site simples com um sistema de assinatura para 10 produtores e 50 clientes iniciais em um bairro específico.",
  "Validação": "Acompanhamento da frequência de pedidos semanais, feedback dos clientes e crescimento do número de produtores inscritos.",
  "Critérios de Aceite": "50 assinaturas ativas, 10 produtores registrados e uma taxa de satisfação de 90% dos clientes.",
  "OKRs": "O: Validar o modelo de negócio; KR1: 50 assinaturas ativas em 3 meses; KR2: 10 produtores na plataforma.",
  "Forças": "Crescente demanda por alimentos locais e orgânicos, forte apelo comunitário.",
  "Fraquezas": "Escalabilidade limitada por espaço físico, desafios logísticos de entrega, dependência de um pequeno número de produtores.",
  "Oportunidades": "Expansão para outros produtos sustentáveis, parcerias com restaurantes e escolas, educação sobre permacultura.",
  "Ameaças": "Concorrência de grandes redes de supermercados, regulamentações locais sobre venda de alimentos, sazonalidade dos produtos.",
  "Resumo": "EcoMercado Urbano é um marketplace que facilita a conexão entre produtores de alimentos em permacultura urbana e consumidores locais, promovendo um sistema alimentar mais justo e sustentável.",
  "Área de Atuação": "Alimentação, sustentabilidade, comunidade, tecnologia.",
  "Nível de Experiência": "Intermediário",
  "Recursos Disponíveis": "Plataforma online, rede de produtores urbanos, lideranças comunitárias.",
  "Prazo Desejado": "4 meses para o lançamento do MVP e validação inicial.",
  "Preço Inicial": "Taxa de assinatura para consumidores, comissão sobre as vendas para os produtores.",
  "Receitas": "Comissão sobre vendas, taxa de assinatura, patrocínios de marcas sustentáveis.",
  "Recursos Disponíveis": "Plataforma online, rede de produtores urbanos, lideranças comunitárias.",
  "Prazo Desejado": "4 meses para o lançamento do MVP e validação inicial.",
  "Critério de Sucesso": "Implementação bem-sucedida em um bairro-piloto e feedback positivo de produtores e consumidores."
  },

  "Assistente de Cozinha por Visão Computacional":{
  "nomeDoProjeto": "Cozinha Inteligente AI",
  "Nome do Projeto": "Cozinha Inteligente AI",
  "Objetivo Principal": "Criar um assistente de cozinha que reconhece ingredientes e sugere receitas, reduzindo o desperdício de alimentos.",
  "Problema": "Muitas pessoas não sabem o que cozinhar com os ingredientes que têm, resultando em desperdício de comida e compra de itens desnecessários.",
  "Solução": "Um aplicativo que usa a câmera do smartphone e visão computacional para identificar ingredientes na geladeira e despensa, gerando receitas personalizadas em tempo real.",
  "Solução Proposta": "Desenvolver um app de assistente de cozinha com IA que reconhece ingredientes, sugere receitas e cria listas de compras inteligentes.",
  "Público/Segmentos": "Pessoas que cozinham em casa, estudantes universitários, casais jovens, famílias que querem reduzir o desperdício de alimentos.",
  "Canais": "Google Play e Apple App Store, marketing de conteúdo em blogs de culinária e redes sociais, parcerias com influenciadores de alimentação saudável.",
  "MVP": "Um aplicativo com capacidade de reconhecer 20 ingredientes comuns e sugerir 50 receitas, com um módulo de lista de compras.",
  "Validação": "Coleta de dados sobre a frequência de uso, número de receitas criadas e feedback dos usuários sobre a utilidade das receitas sugeridas.",
  "Critérios de Aceite": "Reconhecimento de 20 ingredientes com 95% de precisão, 500 downloads no primeiro mês, 50% de usuários retornando semanalmente.",
  "OKRs": "O: Aumentar o uso do app; KR1: 50% de retenção de usuários mensais; KR2: 100 receitas personalizadas criadas por usuário.",
  "Forças": "Tecnologia inovadora, solução prática para um problema comum, potencial para integrações com outros serviços.",
  "Fraquezas": "Desafio técnico do reconhecimento de objetos em diferentes condições de iluminação, custo de treinamento do modelo de IA, dependência de uma base de dados de receitas robusta.",
  "Oportunidades": "Parcerias com supermercados e marcas de alimentos, expansão para o reconhecimento de validade de produtos e automação da lista de compras.",
  "Orçamento Inicial": "R$ 50.000 para desenvolvimento inicial, marketing e testes.",
  "Ameaças": "Concorrência de apps de receitas tradicionais, privacidade e segurança dos dados do usuário, mudanças rápidas na tecnologia de IA.",
  "Resumo": "Cozinha Inteligente AI é um app que usa visão computacional para ajudar as pessoas a cozinhar com o que têm, combatendo o desperdício e tornando a experiência culinária mais eficiente.",
  "Área de Atuação": "Alimentação, tecnologia, inteligência artificial, estilo de vida.",
  "Nível de Experiência": "Avançado",
  "Recursos Disponíveis": "Equipe de desenvolvedores de IA, dataset de imagens de ingredientes, UX/UI designers.",
  "Prazo Desejado": "6 meses para um MVP funcional e validado.",
  "Preço Inicial": "Modelo freemium, com funcionalidades premium para assinatura (ex: receitas exclusivas, reconhecimento avançado).",
  "Receitas": "Assinaturas premium, parcerias com marcas de alimentos, publicidade direcionada.",
  "Critério de Sucesso": "Implementação bem-sucedida do reconhecimento de ingredientes, alto engajamento do usuário e redução do desperdício de alimentos relatada.",
  "Problema Central": "Muitas pessoas não sabem o que cozinhar com os ingredientes que têm, resultando em desperdício de comida e compra de itens desnecessários.",
  "Público-Alvo": "Pessoas que cozinham em casa, estudantes universitários, casais jovens, famílias que querem reduzir o desperdício de alimentos.",
  },
  
  "Mercado de Cursos de Micro-Aprendizagem":{
    
  "nomeDoProjeto": "MicroSaberes",
  "Nome do Projeto": "MicroSaberes",
  "Objetivo Principal": "Uma plataforma onde especialistas podem vender 'micro-aulas' de 1 a 2 minutos sobre tópicos específicos, perfeitas para serem consumidas durante pausas curtas.",
  "Problema": "A maioria dos cursos online é longa e exige um grande investimento de tempo, o que leva à baixa taxa de conclusão e desinteresse.",
  "Problema Central": "A maioria dos cursos online é longa e exige um grande investimento de tempo, o que leva à baixa taxa de conclusão e desinteresse.",
  "Público Alvo": "Profissionais ocupados, estudantes, pessoas que buscam aprender habilidades específicas rapidamente, especialistas que querem monetizar seu conhecimento.",
  "Solução": "Um marketplace de cursos focados em 'micro-aprendizagem', onde o conteúdo é dividido em pequenas pílulas de conhecimento, perfeitas para serem consumidas em pausas curtas do dia a dia.",
  "Solução Proposta": "Desenvolver um marketplace que conecte especialistas a alunos, onde a compra e venda de conhecimento é feita em pequenos módulos de vídeo ou texto.",
  "Público/Segmentos": "Profissionais ocupados, estudantes, pessoas que buscam aprender habilidades específicas rapidamente, especialistas que querem monetizar seu conhecimento.",
  "Canais": "Google Play e Apple App Store, marketing de conteúdo com 'micro-dicas', parcerias com empresas para treinamento corporativo.",
  "MVP": "Uma plataforma web com 5 especialistas e 20 micro-cursos, com um sistema de pagamento simples para aulas individuais.",
  "Validação": "Acompanhamento da taxa de conclusão das micro-aulas, feedback dos usuários sobre a utilidade do conteúdo e a frequência de compras de novos módulos.",
  "Critérios de Aceite": "5 especialistas ativos, 20 micro-cursos publicados e 100 vendas no primeiro mês.",
  "OKRs": "O: Validar o formato de micro-aprendizagem; KR1: 90% de taxa de conclusão das aulas; KR2: 500 compras de micro-aulas em 3 meses.",
  "Forças": "Formato inovador e alinhado com o ritmo de vida moderno, baixo custo de produção para especialistas, alta taxa de conclusão.",
  "Fraquezas": "Pode ser visto como 'conhecimento superficial', dificuldade em construir uma comunidade engajada, concorrência com grandes plataformas de e-learning.",
  "Oportunidades": "Expansão para treinamentos corporativos, criação de 'trilhas' de micro-cursos para certificação, gamificação do aprendizado.",
  "Orçamento Inicial": "R$ 30.000 para desenvolvimento da plataforma, marketing inicial e onboarding de especialistas.",
  "Ameaças": "Youtube e redes sociais oferecem conteúdo gratuito, pirataria de cursos, dependência da qualidade dos especialistas.",
  "Resumo": "MicroSaberes é um marketplace que revoluciona o aprendizado online, conectando especialistas e alunos através de cursos curtos e práticos, perfeitos para a vida moderna.",
  "Área de Atuação": "Educação, tecnologia, e-learning, produtividade.",
  "Nível de Experiência": "Intermediário",
  "Recursos Disponíveis": "Plataforma online, rede de especialistas, ferramentas de gravação e edição simples.",
  "Prazo Desejado": "4 meses para o lançamento do MVP e validação inicial.",
  "Preço Inicial": "Preço fixo por micro-aula ou pacote de aulas (ex: R$5-R$10 por aula).",
  "Receitas": "Comissão sobre as vendas de cada curso, assinaturas para acesso ilimitado.",
  "Critério de Sucesso": "Alto volume de vendas de micro-aulas, feedback positivo de especialistas e alunos, alta taxa de conclusão de cursos.",
  "Descrição Geral": "MicroSaberes é um marketplace que revoluciona o aprendizado online, conectando especialistas e alunos através de cursos curtos e práticos, perfeitos para a vida moderna.",

  },
};
